[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Paint 2 Blocking documentation"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
mathjax-support = true
no-section-label = true
site-url = "/"

[output.html.fold]
enable = false
level = 0
